### PR TITLE
Setup tests, Update docs, and Fix bugs related to binary fetch and string insert/fetch

### LINKED ISSUE #22: Strings with unicode Codepoints 128-255 are truncated when received in MEX
Seems like the culprit is `mxGetString`. 
Should modify to use `mxArrayToString` instead.

### LINKED ISSUE #23: Inserts with strings with unicode Codepoints 128-255 are truncated in tables
Seems the issue is that there is an underlying assumption that characters can be represented in 7-bits i.e. where the Codepoint HEX values and byte HEX values are equal (up to 127). When higher values are utilized, bytes are directly stored as opposed to translated Codepoints.

For instance, when inserting as the following:
```
data = 'ýýýý';
mym('INSERT INTO `djtest_insert`.`test_varchar4` (`id`,`name`) VALUES (0,"{S}") ',data);
```

The result is:

image

### LINKED ISSUE #24: Select of binary data returns strings as opposed to uint8 array
Since inserts of binary data require a one-dimensional array of `uint8`, fetch should reconstruct the `uint8` array and return.

For instance:

```
data = uint8([29, 117, 30, 46, 30, 116, 250, 248, 74, 180, 133, 253, 232, 239, 114, 190]);
mym('INSERT INTO `djtest_insert`.`test_binary16` (`id`,`name`) VALUES (0,"{B}") ',data);
res = mym('select * from `djtest_insert`.`test_binary16`');
disp(res.name{1});
```

image

image

### PR DESCRIPTION
**Pull request by guzman-raphael**
- Fix #22
- Fix #23. Needed to add 2 methods: `char2hex` and `hex2char`. They generate the Codepoints from bytes for storage, and generate the bytes from Codepoints for fetch, respectively.
- Fix #24.
- Bump bugfix version
- Update all mex's
- Update docs
- Setup tests
  - Set UTF-8 encoding to allow tests in certain use cases
  - Add tests for insert/fetch, connection, TLS

### CODE REVIEW

File: src/mym.cpp [hunk 1]
```diff
@@ -945,7 +946,17 @@ void mexFunction(int nlhs, mxArray*plhs[], int nrhs, const mxArray*prhs[]) {
                 }
                 else {
                     tmpPr=mxGetField(plhs[0],0,f[j].name);
-                    mxArray*c = mxCreateString(row[j]);
+                    mxArray*c;
```
Comment (dimitri-yatsenko) [inline src/mym.cpp]:
```suggestion
                    mxArray *c;
```

File: src/mym.cpp [hunk 2]
```diff
@@ -1800,3 +1811,83 @@ mxArray* deserialize(const char* rpSerial, const size_t rlength) {
...
+            result_pnt[idx]=(u0-224)*4096 + (u1-128)*64 + (u2-128);
+            idx++;
+        }
+
+        u3 = original_val[a+3]; 
+        if (u0>=240 && u0<=247) {
+            result_pnt[idx]=(u0-240)*262144 + (u1-128)*4096 + (u2-128)*64 + (u3-128);
+            idx++;
+        }
+        a += l;
```
Comment (dimitri-yatsenko) [inline src/mym.cpp]:
```suggestion
        ++a;
```

File: src/mym.cpp [hunk 3]
```diff
@@ -1800,3 +1811,83 @@ mxArray* deserialize(const char* rpSerial, const size_t rlength) {
...
+        if((a + l) > vlength) l = 1;
+
+        u0 = original_val[a]; 
+        if (u0>=0   && u0<=127) {
+            result_pnt[idx]=u0;
+            idx++;
+        }
+
+        u1 = original_val[a+1]; 
+        if (u0>=192 && u0<=223) {
```
Comment (dimitri-yatsenko) [inline src/mym.cpp]: use hex for all these manipulations to make clear what bits are being compared

File: src/mym.cpp [hunk 4]
```diff
@@ -1800,3 +1811,83 @@ mxArray* deserialize(const char* rpSerial, const size_t rlength) {
...
+
+        u2 = original_val[a+2]; 
+        if (u0>=224 && u0<=239) {
+            result_pnt[idx]=(u0-224)*4096 + (u1-128)*64 + (u2-128);
+            idx++;
+        }
+
+        u3 = original_val[a+3]; 
+        if (u0>=240 && u0<=247) {
+            result_pnt[idx]=(u0-240)*262144 + (u1-128)*4096 + (u2-128)*64 + (u3-128);
```
Comment (dimitri-yatsenko) [inline src/mym.cpp]: use bitshifts instead of multiplication

**Comment by guzman-raphael** [comment]
@dimitri-yatsenko I have made updates based on your feedback.

File: src/mym.cpp [hunk 5]
```diff
@@ -1800,3 +1808,83 @@ mxArray* deserialize(const char* rpSerial, const size_t rlength) {
...
+        }
+    }
+    result_pnt[char_length+offset]= 0x00;
+    return (char *)result_pnt;
+}
+char *char2hex(char *original_val, const size_t vlength, const size_t char_length) {
+    unsigned int idx = 0;
+    unsigned int curr_length = 0;
+    unsigned char u0,u1,u2,u3;
+    uint8_t *result_pnt = new uint8_t[char_length];
```
Comment (ixcat) [inline src/mym.cpp]: not sure about mex programming - do we need to use some matlab allocator to allow matlab to GC memory?

File: src/mym.cpp [hunk 6]
```diff
@@ -1800,3 +1808,83 @@ mxArray* deserialize(const char* rpSerial, const size_t rlength) {
...
+        if (u0 >= 0xC0 && u0 <= 0xDF) {
+            result_pnt[idx] = (((u0-0xC0)<<6) + (u1-0x80));
+            idx++;
+        }
+        if (original_val[a] == 0xED && (original_val[a+1] & 0xA0) == 0xA0) {
+            mexErrMsgIdAndTxt("DataJoint:Serialization:UTF8",
+                "Invalid block of UTF8 detected.");
+        } //code points, 0xd800 to 0xdfff
+
+        u2 = original_val[a+2];
```
Comment (ixcat) [inline src/mym.cpp]: a > &original_val[vlength] ...

this algorithm / loop structure needs to be adjusted to stay w/i array boundaries

File: src/mym.cpp [hunk 7]
```diff
@@ -1800,3 +1808,83 @@ mxArray* deserialize(const char* rpSerial, const size_t rlength) {
...
+            result_pnt[a+offset+1] = ((pnt[a] & 0x3F) + 0x80);
+            offset += 1;
+        }
+        else if(0xD800<=pnt[a] && pnt[a]<=0xDFFF) {
+            mexErrMsgIdAndTxt("DataJoint:Deserialization:UTF8",
+                "Invalid block of UTF8 detected.");
+        } //invalid block of utf8
+        else if(pnt[a]<=0xFFFF) {
+            result_pnt[a+offset] = ((pnt[a]>>12) + 0xE0);
+            result_pnt[a+offset+1] = (((pnt[a]>>6) & 0x3F) + 0x80);
```
Comment (ixcat) [inline src/mym.cpp]: a+offset+1 > char_length

File: src/mym.cpp (hunk 5 above)
Comment (guzman-raphael) [reply src/mym.cpp]: I don't believe it applies here since in C++, only variables defined with `malloc` need to be explicitly freed. Since they are initially defined with `new`, they should be in the stack and destroyed once the function ends.

File: src/mym.cpp (hunk 7 above)
Comment (guzman-raphael) [reply src/mym.cpp]: Yes, this is correct but I am populating and returning `result_pnt`. It is by definition larger in length from argument `original_val` since it represents the HEX bytes. See:
``` cpp
uint8_t *result_pnt = new uint8_t[char_length*4];
```
It has been pre-allocated with the maximum number of elements for a character length (per UTF-8).

File: src/mym.cpp (hunk 6 above)
Comment (guzman-raphael) [reply src/mym.cpp]: I see your point here. I can improve the algorithm to prevent such a scenario.

File: src/mym.cpp (hunk 5 above)
Comment (ixcat) [reply src/mym.cpp]: result_pnt is returned to the caller for subsequent use.. 

(seen elsewhere here in ` mxCreateString(hex2char(row[j], p_lengths[j]));`, etc)

digging further:

https://www.mathworks.com/help/matlab/matlab_external/memory-management-issues.html

indicates there  is some matlab-specific allocator, and it's actually used elsewhere in the code. We should probably be consistent here

File: src/mym.cpp (hunk 6 above)
Comment (ixcat) [reply src/mym.cpp]: curr_length is set based on the user data rather than the memory size and therefore the arrays can be violated  - take for example:

```
char original_val[] = { 0xf0, 0x00 };
````

might not happen in the nominal code path, but should be robust against this problem

File: src/mym.cpp (hunk 7 above)
Comment (ixcat) [reply src/mym.cpp]: Ahh missed this. think we're good.

File: src/mym.cpp (hunk 6 above)
Comment (guzman-raphael) [reply src/mym.cpp]: Ah, I understand now. To illustrate it with a realistic example, we could use the representation of the string `J`. The codepoint for this and the hex bytes are actually equivalent since it is within ASCII. Thus would be:
``` cpp
char original_val[] = { 0x4A, 0x00 };
size_t vlength = 1;
size_t char_length = 1;
```
For this case, the logic would violate the bounds. Thanks man and good catch. I will make an update to include this.

File: src/mym.cpp (hunk 5 above)
Comment (guzman-raphael) [reply src/mym.cpp]: Hmm. I agree on consistency and it is what I was going for. Regarding `char2hex`, seems that I mistakenly removed the `mxCalloc` assignment as it is manually freed in the caller function. I can update this. Regarding `hex2char`, we should be good there as I do not store the result to a variable and simply modify inline the `char` before passing it in to initialize `mxCreateString`.

File: src/mym.cpp (hunk 6 above)
Comment (guzman-raphael) [reply src/mym.cpp]: I have update the logic to address this now.

File: src/mym.cpp (hunk 5 above)
Comment (guzman-raphael) [reply src/mym.cpp]: I have included preallocation to address this now.

File: +tests/+lib/compareVersions.m [hunk 8]
```diff
@@ -0,0 +1,100 @@
...
+    % $License: MIT (use/copy/change/redistribute on own risk) $
+    % $File: compareVersions.m $
+    % History:
+    % 001: 2019-06-12 11:00, First version.
+    %
+    % OPEN BUGS:
+    %  - None 
+    res_n = length(verArray);
+    if ~res_n || max(cellfun(@(c) ~ischar(c) && ...
+            ~isstring(c),verArray)) > 0 || min(cellfun('length',verArray)) == 0
```
Comment (dimitri-yatsenko) [inline +tests/+lib/compareVersions.m]:
```suggestion
            ~isstring(c), verArray)) > 0 || min(cellfun(@length, verArray)) == 0
```
